### ISSUE TITLE
Wacky Races: Ingame menus partially rendered

### ISSUE THREAD

**Issue by Shoegzer** [libretro/flycast#107]
Some game menu elements are rendered but not others, for example:

Reicast:
![wr](https://user-images.githubusercontent.com/12475371/42140183-5e5232e2-7d69-11e8-9726-0d0e27683161.png)

Dreamcast:
![image](https://user-images.githubusercontent.com/12475371/42140196-974bba46-7d69-11e8-94a4-6b000ae8c0d6.png)

Tested on linux x64 against build bbe73d536277a5f170d5c55949a3acc3923a3638

**Comment by inactive123** [comment]
Did you test against both OIT and non-OIT renderers?

**Comment by flyinghead** [comment]
I don't even get any character displayed on the wood panel on my branches. Doesn't look like a renderer problem.

**Comment by Shoegzer** [comment]
@twinaphex actually the problem is worse on the non-OIT renderer (the right-half of the screen is entirely black).  That part's not really too surprising.  Regarding the main issue though, if it's not a renderer problem as @flyinghead says then it may need to be recategorized as something other than a "graphics bugs" issue?

**Comment by flyinghead** [comment]
This game uses double horizontal scaling for antialiasing. So it renders at 1280x480 instead of 640x480. I might have fixed this in the OIT renderer but not the non-OIT one, hence the right half of the screen missing.
I had a look a while back and it seems the missing geometry is not sent to the TA. There's also some FMV sequences missing. Not sure what's going on.

**Comment by inactive123** [comment]
The menu should now be rendered properly as of this commit -

https://github.com/libretro/reicast-emulator/commit/ff8e12c61ceb578c3eca9e0d82efb05fec1acd89

**Comment by Shoegzer** [comment]
Indeed, this has been fixed and I'll close this now.  Incidentally it looks like https://github.com/libretro/reicast-emulator/issues/105 has been fixed too (I assume based on the same commit but haven't bisected to confirm).  I'll close that one as well.

Thanks especially to @flyinghead for this great fix.

**Comment by Deivmsr** [comment]
In the current version of the Reicast core. Wacky Races USA Version: [](url) 
![screenshot_20180817-180507](https://user-images.githubusercontent.com/40547165/44289777-1ba7dc00-a24c-11e8-9d74-d70b1afc7141.jpg)

**Comment by Shoegzer** [comment]
That's a totally different issue.

**Comment by inactive123** [comment]
@Deivmsr Might be fixed in the next core update -

https://github.com/libretro/reicast-emulator/commit/5318a366010efb3019fbd6024fd50e2c8f8b44b3

**Comment by Deivmsr** [comment]
@twinaphex When it will be available?

**Comment by marcrobledo** [comment]
It still happens for me:

![Wacky Races (Europe) (En,Fr,De,Es,It,Nl)-200301-155850](https://user-images.githubusercontent.com/14358263/75628099-0bf5ab80-5bd6-11ea-9780-d45fff26a622.png)

It shows up correctly when setting cable type to VGA.

**Comment by flyinghead** [comment]
It might be a combination of Cable Type/Broadcast/Region settings. Make sure to have them set correctly.
I did a few tests and I can't reproduce it with the latest core.

**Comment by marcrobledo** [comment]
I've tried the PAL game with Region=Europe and Broadcast=PAL (World) with no luck :-(

If you manage to browse into the game options and set the video settings to 60hz, then it shows up correctly. If you set Cable Type to VGA it forces to PAL60, so it shows up correctly from the start.
It doesn't bother me much since I play always with Cable Type=VGA because it forces 60hz in most of 50hz only games. But I figured it could be worth to mention.

(Ignore the 56.90fps from the screenshot. It was running definitely in PAL50, but since I had just left RA menu (which always run at 60fps), it was probably recalculating the average fps).

**Comment by marcrobledo** [comment]
It also happens in Disney's Pixar Buzz Lightyear of Star Command.
Again, PAL game in 50hz. Fortunately, the 50/60 hz selector happens before title screen, so it's easier to play it at 60hz (thus fixing the half screen issue).

**Comment by flyinghead** [comment]
These issues have been fixed a while ago. What's your core version?

**Comment by marcrobledo** [comment]
My fault.

I used the Core Updater a few days ago, but for some reason the core file didn't overwrite.

Tried again and worked. Games are showing up correctly now. Sorry.
