### ISSUE TITLE
Reicast NAOMI multi bios support

### ISSUE THREAD

**Issue by ghost** [libretro/flycast#169]
Hello!

The NAOMI bios is responsible for setting the game region, in order to play games like Marvel vs Capcom 2 and Capcom vs SNK 2 fully in english it's necessary rename a USA bios like epr-21577g.ic27 to naomi_boot.bin. 

Unfortunately this doesn't work in many games like Street Fighter Zero 3 Upper and Capcom vs SNK Pro, a JAP bios is required to boot.

Is it possible to create a NAOMI bios selection option ? That would allow create per game custom settings on RA and select the bios region desired for specific games.

Thanks for all the passion and dedication!

**Comment by barbudreadmon** [comment]
> Is it possible to create a NAOMI bios selection option ?

Possible yes, that's not something i want to do atm though. Too many people will set it to english bios and come opening issues about game incompatible with this english bios not launching.

**Comment by aneronds** [comment]
I understand. Do you think MAME roms could be (also) implemented in the future ? These are more easy to find and for games like MvC2 and CvS2 there's both US and JP versions.

**Comment by barbudreadmon** [comment]
> Do you think MAME roms could be (also) implemented in the future ?

Programming this from scratch is what i've been trying to do the last few days, can't say i'm confident about the fact i'll succeed though, there is a lot to do between implementing roms mappings, reading zip files (@twinaphex i'm having some annoying issue where the core unzip `.bin` files instead of reading the zip files as is, i guess it is related to the fact `.bin` files are allowed extensions), and the various decryption mecanism (which is not really "monolithic" on naomi). I also expect issues with the naomi gdroms since they are chd, and with the real atomiswave roms since they won't be naomi roms anymore.

**Comment by aneronds** [comment]
* fingers crossed * : D 
You will succeed, i'm using chd roms for dreamcast (and all consoles that supports it on RA), it's a really good format What are the contents of the zip files for example of mvsc2 e mvsc2u since the game files are on the gdrom ? Very interesting that the bios is responsible for change de game region (when available). I've been also thinking about the widescreen hack, i have no programming skills but i was thinking if could be possible implement a 4:3 "invisible wall" limit on games in order to hide the extra content at the extreme sides of the image. Marvel vs Capcom 2 for PS3 seems to do that, image doesn't keep going until it's real limit/end, it stops right where the original game limits. I am not sure if i am explaining well.

**Comment by barbudreadmon** [comment]
This feature was implemented months ago when we moved to MAME romsets.
There might be some issues remaining with some roms, please open a new issue if you encounter a problem.
