### ISSUE TITLE
Hokuto no Ken/Fists of the North Star sound looping bug

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/flycast#173]
Music is now looping the first 2s again and again.

1st bad commit is https://github.com/libretro/reicast-emulator/commit/62204c2ca1d96947c3a1b9119ad593d6d52e04d5

@barbudreadmon

**Comment by barbudreadmon** [comment]
It seems prior to this change, because `reios_product_number` was always empty, the AICA interrupt hack from the first line of `lut_games_naomi` was applied to all naomi games...

**Comment by barbudreadmon** [comment]
I created the PR to fix this, keep in mind those hacks are applied by matching with the first line of the lst file, which means you'll need it set to "Fist of the North Star - Hokuto no Ken" (or part of it, that's why the empty string was always considered part of "Street Fighter Zero 3 Upper" and always enabling the AICA interrupt hack), and it seems to be case sensitive.

**Comment by barbudreadmon** [comment]
By the way, if someone know of a case insensitive and cross-platform version of `strstr` (i think `strcasestr` is linux only, not 100% sure though), i think it would save us a lot of trouble in the future...

**Comment by Tatsuya79** [comment]
I did a bisect and didn't get this problem with a prior commit or had to skip any.
My lst name is just "Hokuto no Ken" so perhaps it makes a difference?
The sound is good again now after your PR (with still the previous shorter name).

**Comment by barbudreadmon** [comment]
> The sound is good again now after your PR (with still the previous shorter name).

Yeah, this is ok because "Hokuto no Ken" is part of "Fist of the North Star - Hokuto no Ken".

As i said (perhaps my explanation wasn't clear enough because of language barrier ?), before https://github.com/libretro/reicast-emulator/commit/62204c2ca1d96947c3a1b9119ad593d6d52e04d5, the AICA interrupt hack was applied to every naomi games because `reios_product_number` (which was empty), was always part of "Street Fighter Zero 3 Upper" (first line of `lut_games_naomi`), for which the AICA interrupt hack was enabled.

Now things work in a saner way since we can apply hacks on a per-game basis for naomi, it allowed to fix a few other things (like gfx/sound issues in Metal Slug 6). There is still room for improvement though.

**Comment by Tatsuya79** [comment]
Ok thanks for that fix, closing it.
