### ISSUE TITLE
Reicast crashes upon closing content

### ISSUE THREAD

**Issue by ghost** [libretro/flycast#255]
My BIOS files are in the right places and games load fine, but whenever I exit content, Retroarch just crashes. Its only these cores that do this too (even tested Citra and that exited fine), and it does this with every game.
Emulator: Regular Reicast (OIT does the same thing)
Threaded video on or off: Same Result

**Comment by PixelCrusader** [comment]
Windows 7 64 bit, AMD Radeon HD 6450, Intel i5-2320 CPU @ 3.00GHz
RetroArch 1.7.4 - Reicast 0.1 4a88ea4

I was also experiencing this issue with Reicast 917d3d9, but since updating Reicast to 4a88ea4 and updating RetroArch to the latest nightly, the issue has resolved on my end. 

FWIW, after updating RetroArch I tried using 917d3d9 again and the problem reappeared.

Edit: Upon testing it looks like the crashes have only been resolved when threaded rendering is turned off.

**Comment by flyinghead** [comment]
Closing in favor of #260
