### ISSUE TITLE
RetroArch crashes after trying to close/exit Reicast with threaded rendering enabled

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#260]
@RetroSven This seems to happen again with a latest RetroArch build.

**Comment by RetroSven** [comment]
are you perhaps changing the setting for threaded emu for a game after it has already started?  If so, is that the only way you can make it crash?  If not, then please provide some steps to reproduce.

**Comment by inactive123** [comment]
1) Start up core and game
2) Try to exit

It crashes

Scenario 

1) Startup core and game
2) Go to Quick Menu
3) Select Close Content

It crashes instead of exiting the core/game and returning back to RA menu.

**Comment by RetroSven** [comment]
There must be something else going on because I had done that literally dozens of times before asking for steps.  Is this with the non-oit core or the oit variety?  I can't run the OIT version so I have no way of debugging if that's the case.  If you get the same thing with non-OIT, then attach the reicast cfg you're using and the game(s) with which this happens.

**Comment by inactive123** [comment]
No, I get the same issue with Reicast Libretro and Reicast OIT Libretro. Very same crashes on Window 10 when selecting 'Close Content'.

There is definitely an issue here.

**Comment by inactive123** [comment]
retroarch-core-options.cfg -

https://hastebin.com/zeyupecusi.ini

**Comment by RetroSven** [comment]
This actually has nothing to do with any of the recent changes to reicast or RA.  This problem has existed ever since threaded rendering was first implemented, but it manifests itself in a transient manner.  That's why it may have seemed like it worked at some point.  This all relates to the threading problem when trying to save states from the main menu.  When you enter the main menu, the reicast cpu thread will "pause" because it will either block on the video rendering mutex or on the audio rendering mutex.  When it pauses on video rendering mutex, reicast can clear that mutex itself so it's not a problem.  When it pauses on audio rendering mutex, reicast cannot clear that itself because it has no way to do so via libretro API.  I've added another environment variable to handle this - new PRs coming for RA and reicast

**Comment by PixelCrusader** [comment]
Windows 7 64 bit, AMD Radeon HD 6450, Intel i5-2320 CPU @ 3.00GHz
RetroArch 1.7.4 2a7a2e7dee - Reicast 0.1 514c569

Closing games with threaded rendering enabled no longer causes RetroArch to crash. #255

**Comment by inactive123** [comment]
Are you using the latest nightly of RetroArch or the latest version compiled from source?

**Comment by PixelCrusader** [comment]
Yes. I used the nightly update from within the desktop UI.

Closing games is working fine on my end.

**Comment by RetroSven** [comment]
@PixelCrusader the "too fast" issue is symptomatic of an updated Reicast core but an old RA.  Please double check that the RA executable you're running is the bleeding edge.

**Comment by PixelCrusader** [comment]
I'm apologize but this conversation is starting to become a bit confusing.

@RetroSven Hydro Thunder was running at the proper speed when I updated RetroArch with the desktop UI's online updater (I wasn't in the habit of recording the git version yet, but it happened on September 5th) and launched it with Reicast 917d3d9 a week ago. I noted this in #171.

The reason I made the reference is because now Hydro Thunder isn't running at all. Today, Using the Desktop UI, I updated RetroArch to Git version 2a7a2e7dee and updated Reicast to 514c569. Games using threaded rendering are now properly closing when threaded rendering is enabled. Hydro Thunder doesn't go past the Dreamcast start up screen at all now.

Just now, I've updated RetroArch with the online updater within the program again. It is now Git version: 7428fef4bc with a build date of Sep 12 2018. The latest Reicast is still 514c569. I can't get anything more recent than that without learning to do the compiling myself.

Closing games with threaded rendering activated is still working properly now. Hydro Thunder is still unplayable. I was wondering if there was a connection.

**Comment by blackman91** [comment]
RetroArch also crashes with the reicast core this way:
https://github.com/libretro/reicast-emulator/issues/272

**Comment by flyinghead** [comment]
Assuming this is fixed. Reopen as needed

**Comment by MukiEX** [comment]
It does indeed still crash after closing content, as of April 2020 builds.

**Comment by ds22x** [comment]
It still crashes for me after closing content, with or without the threaded renderer enabled, regardless of vsync or video driver or even emulator settings, when using the latest Flycast on my computer (previously running Win10 1906, now running 2004 with no difference whatsoever) with the following CPU and GPU specs:
- Intel Core i5-9300H @ 2,4GHz with a max of 4,1GHz
- Nvidia GTX 1650 with the latest drivers v456.71
