### ISSUE TITLE
Games crash due to unimplemented opcode

### ISSUE THREAD

**Issue by Eds1989** [libretro/flycast#350]
I have several games that when trying to load in the Reicast core, I get the BIOS and the Sega license logo, but then crash due to an "Unimplemented Opcode".

I have pasted the console output of when this occurs below.
Is this due to general compatibility, and issue with my ROM, or the BIOS I am using?

`reios: Area symbols is: JUE
reios: Peripherals is: 0799810
reios: Product number is: T42101N 00
reios: Product version is: V1.003
reios: Release date is: 20000110
reios: Boot filename is: 0WINCEOS.BIN
reios: Software company is: ECHELON
reios: Software name is: WILD METAL                                                                                     
reios: loading ip.bin from FAD: 63512
reios: bootfile is '0WINCEOS.BIN    '
reios: iso9660 PVD found
reios: iso9660 root_directory, FAD: 63535, len: 2048
[libretro ERROR] Failed to locate bootfile.
[libretro INFO] [LUT]: Product number: T42101N 00.
Get MemPtr unsupported area : addr=0xA0000000
Get MemPtr unsupported area : addr=0xA0000018
Freeing fpcb
Get MemPtr unsupported area : addr=0x80000080
Get MemPtr unsupported area : addr=0x800000A8
Get MemPtr unsupported area : addr=0x800000BE
Get MemPtr unsupported area : addr=0x800000C6
Freeing fpcb
Invalid GD-DMA start, SB_GDEN=0.Ingoring it.
MODEM Reset
sh4io: Invalid read access @@ 00000030
Freeing fpcb
Invalid GD-DMA start, SB_GDEN=0.Ingoring it.
Freeing fpcb
Freeing fpcb
new tactx
new tactx
Freeing fpcb
Freeing fpcb
Freeing fpcb
Freeing fpcb
Freeing fpcb
Freeing fpcb
Freeing fpcb
MEM remap 0 : 0x5800 to 0xC345800
Get MemPtr unsupported area : addr=0x5B90
Get MemPtr unsupported area : addr=0x67EC

Unimplemented opcode: 00004DC8 next_pc: 000067F2 pr: 00005B94 msg: Unknown opcode
[libretro INFO] Fatal error : iNimp reached

 in cpu_iNimp -> core/hw/sh4/interpr/sh4_opcodes.cpp : 66
DEBUGBREAK!`

**Comment by flyinghead** [comment]
> reios: Boot filename is: 0WINCEOS.BIN

Windows CE games are not supported

**Comment by Eds1989** [comment]
Is there a way to identify these ahead of times, or do I just look for this line when launching the game:
reios: Boot filename is: 0WINCEOS.BIN

**Comment by blisstik** [comment]
Google dreamcast wince sega retro

________________________________

**Comment by Eds1989** [comment]
Will do.
Is support for these on the roadmap?

**Comment by ghost** [comment]
Also, you using a ECHELON scene rip of the game? Dev of game was Rockstar/DMA Design.....

**Comment by ubergeek77** [comment]
Edit: Actually, this is happening on every game I throw at it. Maybe this is a Windows-specific regression? Games run fine on Android, but I want to try out pixel-accurate OIT.

Edit2: I just tried loading a handful of different games on two completely different Windows computers. Both are behaving exactly the same, and I get the "unimplemented/unknown opcode" error.

Edit3: I tried loading games on MacOS using the same build of this core, built against commit dfe8d3c. It works. Whatever this issue is, it seems to be Windows-specific.

---

I'm seeing this same error when trying to load Sonic Shuffle using this core on Windows. And I definitely have the BIOS files in the right place:

`reios: Hardware ID is: SEGA SEGAKATANA`
`reios: Maker ID is:    SEGA ENTERPRISES`
`reios: Device info is: 188D GD-ROM1/1`
`reios: Area symbols is:  U`
`reios: Peripherals is: 0799810`
`reios: Product number is: MK-51060`
`reios: Product version is: V1.000`
`reios: Release date is: 20001019`
`reios: Boot filename is: 1ST_READ.BIN`
`reios: Software company is: SEGA ENTERPRISES`
`reios: Software name is: SONIC SHUFFLE                                                                                  `
`reios: loading ip.bin from FAD: 45150`
`reios: bootfile is '1ST_READ.BIN    '`
`reios: iso9660 PVD found`
`reios: iso9660 root_directory, FAD: 45170, len: 2048`

(Skipped some INFO lines about controller mappings)

`Get MemPtr unsupported area : addr=0xA0000000`
`-----------------`
`REIOS: Booting up`
`-----------------`
`Freeing fpcb`
`Unimplemented opcode: 0000FFFF next_pc: AC008302 pr: AC00043C msg: Unknown opcode`
`[libretro INFO] Fatal error : iNimp reached`
 `in cpu_iNimp -> core/hw/sh4/interpr/sh4_opcodes.cpp : 66`
`DEBUGBREAK!`

This doesn't happen on the standalone Reicast for windows .exe, but the graphical glitches are pretty bad there, and I don't see a way to configure graphics settings.

**Comment by flyinghead** [comment]
You need to install dreamcast BIOS files

**Comment by ubergeek77** [comment]
Edit:
This is weird. Now the 64 bit version of RetroArch is working for me, but the 32 bit version of RetroArch is crashing with a different error (unhandled access to 0xA0000000). I just double checked, and everything is in the right place. MD5Sums for dc_bios.bin and dc_flash.bin are correct. The internal RetroArch option for the "System/BIOS Directory" is correct, and there are even 4 "vmu_save_X1.bin" files next to where I have the BIOS files.

I'm really not sure what happened, but now the 64 bit version is working for me, and I don't have a reason to use the 32 bit version, so my issue is resolved. Thankfully this issue was originally about Windows CE games not working anyway, so I hope I didn't cause too much confusion 😛 


--Original comment:--

I have the Dreamcast BIOS files. I'm almost positive they are in the right
directory too. I'll double check the path of the RetroArch System folder,
but I had the same setup on my MacOS machine and didn't have these loading
problems.

Both BIOS files (BIOS and flash) were in /system/dc/, and only Windows has
this loading problem. They were in the same location on the MacOS machine
and it loaded fine. On my main Windows machine, I've reinstalled RetroArch
into different directories to no avail, even trying x86 and x86_64 versions.
