### ISSUE TITLE
reicast_oit_libretro.so crashes on mesa

### ISSUE THREAD

**Issue by toccata10** [libretro/flycast#41]
retroarch -L ~/.config/retroarch/cores/reicast_oit_libretro.so ~/Arcade2/Roms/dreamcast/Power_Stone_2\(USA\).gdi
it crashes with:
```
[libretro INFO] Using Recompiler
Sh4 Reset
recSh4 Init
@@      ngen_ResetBlocks()
Freeing fpcb
Shader: failed to compile 
0:1(10): error: GLSL 4.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

Shader linking: failed to link 
 (51 bytes), - error: linking with uncompiled/unspecialized shader -
[libretro INFO] Fatal error : shader compile fail

 in gl_CompileAndLink -> core/rend/gl4/gles.cpp : 484 
DEBUGBREAK!

```
I also tried with:
MESA_GLSL_VERSION_OVERRIDE=450 MESA_GL_VERSION_OVERRIDE=4.5COMPAT
but same result.
r9 fury, mesa 18.1.1, archlinux
Non oit version is working.

**Comment by inactive123** [comment]
Seems your GPU supports GL 4.5, so I think what it needs is core context for 4.3.

**Comment by inactive123** [comment]
Core context is not happening for now until we can fix all the bugs that happen with it turned on.

**Comment by barbudreadmon** [comment]
I confirm i have the same issue with mesa (intel card with vulkan support so i guess it supports all opengl versions). On a sidenote, it is running fine on my other computer with nvidia proprietary driver.

**Comment by inactive123** [comment]
Somebody gave me this log -

https://cdn.discordapp.com/attachments/434713532341288961/456553092566220822/retroarch-log.txt

We could need some GL experts to tell us what is behind this. It works fine on nvidia.

**Comment by flyinghead** [comment]
I guess this is the line that the Intel driver doesn't like (gles.h):
`layout(size1x32, binding = 4) uniform coherent restrict uimage2D abufferPointerImg;`
The image is created in abuffer.cpp:
```
//Uses GL_R32F instead of GL_R32I that is not working in R257.15
glTexImage2D(GL_TEXTURE_2D, 0, GL_R32F, g_imageWidth, g_imageHeight, 0, GL_RED, GL_FLOAT, 0);
```
It's created as a single-channel, float image, but used as an unsigned int supposedly because some version of the Nvidia driver had a bug. That might not be true anymore for recent Nvidia drivers and that may be the reason why the Intel driver is complaining.
I would try to change GL_R32F in the glTexImage2D call to GL_R32UI to see if recent Nvidia drivers accept it. That could fix the Intel driver problem as well.

Another thing to try would be to add r32ui in the layout qualifier like this:
`layout(size1x32, r32ui, binding = 4) uniform coherent restrict uimage2D abufferPointerImg;`
Perhaps also remove the size1x32 qualifier since it seems redundant.

Sorry for not being more helpful for now but I don't have access to my dev environment.

**Comment by inactive123** [comment]
@flyinghead Was the issue you were experiencing a very slow red screen? Because that is pretty much what I am experiencing on current Windows nvidia drivers unfortunately.

**Comment by flyinghead** [comment]
@twinaphex Sorry I don’t remember. Will look at this when I get back.

**Comment by inactive123** [comment]
Alright, no problem. Thanks for your help.

**Comment by rcaridade145** [comment]
@twinaphex @toccata10  https://phoronix.com/scan.php?page=news_item&px=GL45-Compat-RadeonSI-Start Seems support is coming.

**Comment by toccata10** [comment]
I tried compiling the latest retroarch version + updated to the latest reicast_oit: oit now works (but there's a big performance hit, even on a i7 4770k (but pushing also to 4k...): virtua tennis 2 plays perfectly at 4k with the "normal core", but there are big slowdowns with the "oit core").
I'd prefer to let this bug open as retroarch is at version 1.7.3
When a new version is released, this bug can be closed.
Similar to #167

**Comment by barbudreadmon** [comment]
@toccata10 i don't understand, are you saying the crash is resolved but you don't want to close this issue because it doesn't perform well at 4k resolution ?

**Comment by toccata10** [comment]
@barbudreadmon : no, I'm just saying that the crash will be resolved when the next version of retroarch is released. I don't expect users to use the latest git: I expect them to use the current upstream version. So with the retroarch version 1.7.3, the oit_core crashes with mesa. But if @twinaphex prefers to consider it solved now and close it, that's allright. I'd prefer to close it when it's working out of the box for a lambda user using the latest "stable" version, but it's not very important.

**Comment by barbudreadmon** [comment]
@toccata10 ok, so you are saying it is running without crash as long as you use latest git retroarch ? 
What about performance ? Are they normal if you are at standard resolution ?

**Comment by toccata10** [comment]
@barbudreadmon yes, that's it. On an i7 4770k, r9 fury, ArchLinux: VirtuaTennis2: 
- 640x480 and 1280x960: perfectly fluid
- 1920x1440 has few slowdowns (mostly on videos and selection screen), but remains very playable.
- 2560x1920: inside the game it's mostly ok, but severe slowdowns (down to 37fps) on selection screen + some transitions: not a very pleasant experience. 
With the non_oit_core,  it's always super fluid (no slowdown), whatever the resolution.

**Comment by barbudreadmon** [comment]
Well, the oit core is quite demanding, even on good hardware, i have an intel core i7 myself and i can't say every game i tried ran smoothly, even at standard resolution, notably a few shmups on naomi. I don't think there will be much progress about this as long as multi-thread is broken in libretro-reicast.

**Comment by inactive123** [comment]
Multithreading would need to be looked into by somebody more skilled than me at both GL and multithreading.

**Comment by barbudreadmon** [comment]
Isn't @flyinghead skilled in this ?

**Comment by barbudreadmon** [comment]
@twinaphex @flyinghead For what it's worth, multi-thread seems to crash on this : 
https://github.com/libretro/reicast-emulator/blob/2d411a166d8fa4a4cc5f0cb23c3f60537774333d/core/libretro-common/glsm/glsm.c#L2582

I tried adding printfs before and after this line, the first would show, the second wouldn't.

**Comment by barbudreadmon** [comment]
Most likely, the OpenGL calls aren't executed on the renderer thread (or something along those lines).

**Comment by rcaridade145** [comment]
@twinaphex  @flyinghead mentioned that on #46 .

**Comment by barbudreadmon** [comment]
I'm not sure how to implement this here, but it seems to me like those 2 lines from the standalone version are what we are missing in the libretro port : 

https://github.com/reicast/reicast-emulator/blob/a5cf5406cbbaf9dd849a56871ad48ddec0676377/core/rend/gles/gles.cpp#L554-L555

When i google "opengl multi thread", i see mentions to `wglCreateContext` and `wglMakeCurrent` everywhere

**Comment by inactive123** [comment]
Well, with libretro you don't have to use GL context APIs like WGL or GLX, that is handled on the frontend side. However, we might need to be able to query the equivalent of a wglMakeCurrent call. 

@aliaspider would likely know more since he has dabbled with multithreaded GL renderers in both Dolphin and PPSSPP.

**Comment by flyinghead** [comment]
The Open GL context needs to be accessed by a single thread AFAIK. However OpenGL operations happen asynchronously, when possible.

Something that could help would be to do texture conversion on the GPU side: palette lookup, untwiddling, YUV conversions... And in the future: filtering, upscaling and what not.

This phase of rendering blocks the emulator thread, because we don't want any write to VRAM while we're uploading textures. So the faster we can do texture conversion and upload the better.
I don't know how much there is to gain here though.

**Comment by toccata10** [comment]
retroarch 1.7.4 is out. The problem is solved on this latest stable version. Thanks.
