### ISSUE TITLE
Support new redump.org CUE format dumps

### ISSUE THREAD

**Issue by RibShark** [libretro/flycast#457]
Redump.org has replaced the GDI format in their database with an extension of the CUE format, due to redump's dumps storing extra data that the GDI format is not equipped to support (previously, redump was misusing the GDI format to achieve support, [see here for a detailed explaination](https://assemblergames.com/threads/wrote-a-tool-for-gdemu-users-for-converting-redump-gdi-format-to-general-gdi-format.66263/#post-942906)).

The new .cue format as well as the discussion leading to its creation can be found in [this thread](http://forum.redump.org/topic/19969/sega-dreamcast-multicue-gdi/), but in essence the format simply puts each track sequentially, using `INDEX 00` and `INDEX 01` for the pregaps, and adding a comment (`REM SINGLE-DENSITY AREA` and `REM HIGH-DENSITY AREA`) to distinguish the two areas of the disc.

Example cuesheet:
```
REM SINGLE-DENSITY AREA
FILE "Championship Surfer (Europe) (En,Fr,De,Es,It) (Track 01).bin" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
FILE "Championship Surfer (Europe) (En,Fr,De,Es,It) (Track 02).bin" BINARY
  TRACK 02 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
REM HIGH-DENSITY AREA
FILE "Championship Surfer (Europe) (En,Fr,De,Es,It) (Track 03).bin" BINARY
  TRACK 03 MODE1/2352
    INDEX 01 00:00:00
FILE "Championship Surfer (Europe) (En,Fr,De,Es,It) (Track 04).bin" BINARY
  TRACK 04 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Championship Surfer (Europe) (En,Fr,De,Es,It) (Track 05).bin" BINARY
  TRACK 05 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Championship Surfer (Europe) (En,Fr,De,Es,It) (Track 06).bin" BINARY
  TRACK 06 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Championship Surfer (Europe) (En,Fr,De,Es,It) (Track 07).bin" BINARY
  TRACK 07 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Championship Surfer (Europe) (En,Fr,De,Es,It) (Track 08).bin" BINARY
  TRACK 08 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Championship Surfer (Europe) (En,Fr,De,Es,It) (Track 09).bin" BINARY
  TRACK 09 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Championship Surfer (Europe) (En,Fr,De,Es,It) (Track 10).bin" BINARY
  TRACK 10 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Championship Surfer (Europe) (En,Fr,De,Es,It) (Track 11).bin" BINARY
  TRACK 11 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Championship Surfer (Europe) (En,Fr,De,Es,It) (Track 12).bin" BINARY
  TRACK 12 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Championship Surfer (Europe) (En,Fr,De,Es,It) (Track 13).bin" BINARY
  TRACK 13 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Championship Surfer (Europe) (En,Fr,De,Es,It) (Track 14).bin" BINARY
  TRACK 14 MODE1/2352
    INDEX 00 00:00:00
    INDEX 01 00:03:00

**Comment by i30817** [comment]
I wish TOSEC changed their 'standardized' gdi track names instead (they cause hashsums of gdi files to be almost all duplicates because the interior content of gdi files only references track names and offsets).

**Comment by wingedonezero** [comment]
I would also like to see support added. I figured it'd work out of the box since the changes but i couldn't get a single game to load without the gdi. From what i understand the change had to happen at some point and its for the best since redump is almost at a full collection for dc. I also read its suppose to be more accurate or something as well. Makes sense to me to though most disc based systems are bin and cue already gdi was kinda the outlier.

**Comment by i30817** [comment]
chd support would be better, because chd has a sane internal checksum that is actually unique.

**Comment by wingedonezero** [comment]
Myself and many other prefer redump though their is a thread on here asking for support of chd already i believe. I personally hate chd i prefer bins and cues or isos. Redump has always done right by me and i trust them same as nointro. Plus most disc based systems are bin and cue already so adding this support would make more sense.

**Comment by i30817** [comment]
>  I personally hate chd i prefer bins and cues or iso

Nah. CHD basically a saner version of zip+cue/bin, only with what's needed to uniquely identify the games and can be extracted to the same bytes again. 

Neither CHD or MAME are redumping cd based consoles, instead they're saying 'zip is a stupid horrendous format for these consoles, we will just take the redump dumps and use chd to wrap them in sanity'.

If you 'hate' it, it's because redump DATs are not including the chd 'data sha1' which can be parsed directly¹. Which is stupid of them but hopefully retroarch will start to include it on the MAME database and we'll get it that way, and hopefully it can be associated to other emulators than mame.

The whole reason for all of these problems (except the 'zip isn't random access' problem) is that the originators of the 'dump DAT format' screwed up and never thought a 'ROM' could be more than one file (or if they did, they thought it was appropriate to have the checksum of the zip as 'standing in' for that multifile rom). 

Turns out this last is a terrible idea if you want multiple compression levels, thus all the MAME arcade roms needing to be 'torrentzipped' to be recognized. They're keen on not repeating that mistake.

Also it's a good idea if *something* standardizes a internal checksum and the MAME and CHD 'data sha1' is one that is already done. This way all kinds of compression formats can standardize on 1 checksum type for the summation of the data bytes.

¹(much like you can get 'fast' crc32 on a zip for single files, but better because this is for all of the game bytes, and is thus _actually unique_ without false positives)

**Comment by wingedonezero** [comment]
You obviously love Chd's lol. Im not against them adding support for those but that's not what this thread is about. Most people who collect sets collect in bin and cue for disc based games or iso.. And personally i don't care about the supposed space savings multicompression gives. It may be fine for Mame but like i said most all rom collections are in bin and cue for all disc based systems and they are fine. I can zip or 7 zip if im worried about space which i am not.

**Comment by i30817** [comment]
You'd be wrong with that, i don't (appear to) compress my dumps. I don't because retroarch has abyssal support for chd **and** zip (see the missing 'data sha1' and their terrible idea of decompressing whole games to read serials or play them, which is more or less obligatory for zips but not chd).

But i'm also not going to pretend zip is better. I don't have a opinion about if reicast should support cue, except in so far as i'd vastly prefer that the dumping groups and retroarch got their head out their ass and allowed me to scan and use chd instead without their code deciding i need to write a few gigabytes to disk in order to play a game or scan a serial when the format can stream/random access fine.

I use on disk compression instead. It's terrible for scanning (because it has to calculate it instead of picking up a checksum from the zip or the chd), but at least i'm sure i'm not writing trash to disk everytime i play a game because retroarch is unable to stream a streamable format.

**Comment by wingedonezero** [comment]
I get what your saying. Im not trying to argue whats better or worse. Zip isn't really that bad its fast for viewing or reading and exacting which i think is one of its strong suits. 7zip lzma is better for compression but a lot slower to read from and extract depending on level. So i understand for the want of the chd as kind of a middle ground i guess you could say. 

I personally store rips on a separate archive hdd and what im playing extract to a game drive. And i 7zip the files in my archive with a 100@ par2 recovery as well. But like i said to stay on topic for disc based games bin and cue all the way and a lot of people feel that way. Chd support should be in its own thread.

**Comment by flyinghead** [comment]
redump.org CUE file format is now supported
