### ISSUE TITLE
Vibration motors staying on

### ISSUE THREAD

**Issue by Nine-H** [libretro/flycast#47]
I tested cannon spike and zero gunner 2 and the rumble motors just stay on constantly.

**Comment by hiddenasbestos** [comment]
I've found the same with the opening 'engine rev' in F355 Challenge. It's more than just Psikyo games.

Looking at a copy of the SDK and in one of the samples there's a couple of different flags for the rumble on the game side:

PDD_VIB_FLAG_EXHALATION
PDD_VIB_FLAG_CONVERGENCE
PDD_VIB_FLAG_CONTINUOUS

I have a feeling that one or both of the first two flags might cause the Dreamcast to automatically fade out its rumble over time - if that's not emulated correctly then it perhaps explains why it's staying on.
I'm not really sure how to fix that but hopefully it shines a light on the problem.

As a workaround you can open the Quick Menu and it should stop the residual vibration.

**Comment by Nine-H** [comment]
alright, I changed the title of the bug.

**Comment by rcaridade145** [comment]
PurupuruPack must be enabled by default. Took a look into the source don't seem to find where it changes vibration :|

**Comment by Metasynic** [comment]
After messing around for a while (on Sonic Adventure 2 - controller starts vibrating and won't stop when Knuckles or Rouge climb on a wall) I found a quick way to clear out the vibration signal. Going into the RetroArch "Quick Menu" (F1 by default) and out again fixes it until the next time the game tells the controller to start vibrating. I suggest assigning it to something on your controller (I have L3+R3) to make things easier until the bug is fixed.
