### ISSUE TITLE
Naomi input descriptors

### ISSUE THREAD

**Issue by Dogway** [libretro/flycast#514]
A ticket for the following issue.
"mazan and ninjaaslt both use very specific I/O input boards so more work is needed in this area."

https://github.com/libretro/reicast-emulator/pull/400
https://github.com/libretro/reicast-emulator/issues/399

Also crackndj needs the I/O board fixed, and input descriptors included.

**Comment by blisstik** [comment]
@eckso - I'm guessing you were testing these games for using a mouse. They do not work for me. I was wondering if you had a chance to test House of the Dead 2 **using a mouse** which works using the L3 analog stick for Playstation style controllers.

**Comment by Dogway** [comment]
With hotd2 controls work out of the box, the crosshair is not visible but I can point with left stick and shoot with A button while holding RB (X360 controller). Now, I'm using ram saves previously configured in another emulator. btw, I think ram saves should be {dumpname}.sram not as the current {dumpname}.{ext}.sram

**Comment by blisstik** [comment]
Have you tried mouse?

________________________________

**Comment by Dogway** [comment]
I tested and it didn't work (out of the box), although I'm not the best configuring the controls in latest versions, it's quite a mess, input descriptors lacking also here, reicast freezing when resuming from GUI, etc.

**Comment by flyinghead** [comment]
Closing in favor of #524

**Comment by MrPinballHands** [comment]
Guys I have this and I am super interested in seeing if it would be possible to hack into this.

Pretty much exactly what this game would use.

Independent 'vinyl' of motorized turntables with fader. It's midi - anyone smarter than me wanna help me get it paired up?
Will come back when I play around with it. I havent ever got it to launch before today so that's cool.

https://www.sweetwater.com/store/detail/RANEONE--rane-rane-one-2-channel-motorized-dj-controller

Different than most dj usb controllers as the decks are motorized and there's almost like a control vinyl  but its latched with a key sort of...

**Comment by flyinghead** [comment]
This repo is inactive. Use the upstream repository to report issues or ask for enhancements: https://github.com/flyinghead/flycast/issues.

To answer your question, everything is possible. See this video for a proof of concept: https://www.youtube.com/watch?v=wknVcHx0164
Unfortunately, there's no standard API or protocol to work with these DJ controller devices so code must be written for each device type. This is just too much work for just 2 games.
