### ISSUE TITLE
Naomi lightgun emulation broken

### ISSUE THREAD

**Issue by cubatilles** [libretro/flycast#537]
Hello,
I don't know when this isue appeared, but since some versions ago (it's happening with latest build and also with a build from 21st april), any naomi lightgun game doesn't work when using Lightgun as input method.

When using gamepad as input method everything works fine, but of course then the aiming is controlled via leftjoystick, which is errible for a lightgun game. I play these lightgun games using a mouse (well not really, I'm using a DS4 using gyros to emulate mouse input), and now it's impossible. I've done a lot of tests, tried a clean install, removed my eeprom data and tried recalibration. Tried also with latest retroarch build from today, always same result.

Apparently, the gun trigger works but aiming doesn't. If I enter maze of kings' service menu, when in gun calibration screen, no matter what am I aiming at, it always give the value "80H".

Tested this with Lupin Shooting and confidential mission, too. It happens with any naomi lightgun game.

Greetings.

**Comment by flyinghead** [comment]
The fix for #552 might fix this issue as well. I can't test right now. Can you give it a try?

**Comment by flyinghead** [comment]
Yes, it looks like this is fixed as well. Please confirm.

**Comment by cubatilles** [comment]
Aha! Yeah it's fixed man! Thanks, thank you so much @flyinghead ead. I'll close this.

**Comment by mantis-droid** [comment]
Hello - I actually wanted to report that it appears I'm having a similar problem using the latest build of the Flycast core. Specifically with Maze of Kings I'm getting "00H" instead of "80H" though. Similar behavior seems to be taking place with HOTD2, Ninja Assault, etc. Has anyone been able to resolve the issue previously? I'm wondering if there was a method for resolving this if it has been previously posted. Thanks for the help
