### ISSUE TITLE
Atomiswave 720p with character tear line

### ISSUE THREAD

**Issue by dewenhsu** [libretro/flycast#618]
For example, the game : Dolphin Blue, at the start  atomiswave logo has tear line in 720p resolution, so as Samurai Showdon 6, the character have tear line in 720p and 1080p, but normal in 960p. 
Running Odroid N2 TheRA.

**Comment by dewenhsu** [comment]
https://www.dropbox.com/s/ii0g9yqbbgsjmvt/IMG_0122.JPG?dl=0
https://www.dropbox.com/s/uhj5yo6dozu9851/IMG_0116.JPG?dl=0

**Comment by flyinghead** [comment]
Atomiswave games are supposed to run at 640x480. Upscaled resolutions can produce artifacts such as the ones you describe. And it is more likely to happen with non-multiples of the original resolution such as 720p (x1.5) or 1080p (x2.25).

**Comment by darksaviorx** [comment]
Not sure if it's related. I only get this issue with the sprites in SFZ3 Upper. I'm using a pi4 with the flycast build script from here: https://github.com/RetroPie/RetroPie-Setup/blob/fkms_rpi4/scriptmodules/libretrocores/lr-flycast.sh
![Street Fighter Zero 3 Upper-191007-011101](https://user-images.githubusercontent.com/13961313/66278301-8bb45f80-e85c-11e9-94a9-ebfbcbde4997.png)

Changing resolution has no effect but I use 1080p output otherwise retroarch menu is hard to use. It used to be fine but maybe a recent update caused it.

I tested a few naomi/atomiswave where they visually look fine (well, some run at 10fps and used run at 30fps like metal slug6 "blood" version before the wince update but that's another issue for another day): naomi, atomiswave bios boot logos, dolphinblue, fotns, mvc2, cvs1 and 2, samsho6, metalslug6, meltyblood, ggisuka, gg accent core.
