### ISSUE TITLE
(OIT-only) Unreal Tournament - corrupted textures (black bars)

### ISSUE THREAD

**Issue by mlnlbrt** [libretro/flycast#78]
There are thin black bars on some textures (memory corruption?):

![unreal tournament usa -180630-085317](https://user-images.githubusercontent.com/11428910/42122656-5bf4e3e8-7c45-11e8-9c45-33fa0b5e7615.png)
![unreal tournament usa -180630-085335](https://user-images.githubusercontent.com/11428910/42122659-6554d664-7c45-11e8-8f85-ccf058bbbb18.png)
![unreal tournament usa -180630-085411](https://user-images.githubusercontent.com/11428910/42122660-6c59e6f2-7c45-11e8-837b-b9c73617e6bd.png)

This glitch is not present with non-OIT core. GPU nVidia GT 1030 (binary drivers) + Linux

BTW It seems there is a performance bottleneck with UT (for both non-OIT and OIT cores), because I have tried it on different configs and it runs at about 80% of game speed and has crackling audio on every of them:

- CPU c2d ~3.8 GHz, GPU Radeon HD3450, Linux
- CPU c2d ~3.8 GHz, GPU nVidia GT 1030 (binary drivers), Linux
- CPU pentium g2120 3.1 GHz, integrated GPU, Linux

as you can see it is probably not lack of GPU power (HD3450 vs GT 1030 on the same CPU gives the same performance for UT), just something else. Is it a known problem?

**Comment by inactive123** [comment]
I can confirm this.

Also, you need to set Cable Type to VGA (RGB) in order for the game to work (at least with the copy I am using).

I can also confirm that this game for one reason or another seems to have higher system requirements than other games.

**Comment by mlnlbrt** [comment]
@twinaphex I don't know at which exact commit it started to happen, but with https://github.com/libretro/reicast-emulator/commit/5c4135905a600e05c3d5b4722c5accd89b01ed18 the speed got even worse (non-OIT, I haven't checked OIT).

**Comment by flyinghead** [comment]
FYI I do see the black bars in the OIT libretro core but I don't have this issue on my branch.
It doesn't seem to be a texture corruption.

**Comment by inactive123** [comment]
@mlnlbrt Yes performance took a massive nosedive with the non-OIT renderer unfortunately due to the implementation of flat shading (which Evolution seems to require).

I have really been banging my head against the wall on how we are going to add this performance back and how we can make flat shading a runtime option.

@flyinghead Is it perhaps possible you can add this as a runtime option in the non-OIT renderer and you could then also see how much performance difference there is with it turned on/off? Because I think I easily estimated 50 to 100fps loss due to this, but your mileage may be different in your branch, and maybe I just backported something wrongly. But I can't see what though.

The main reason why I fear adding this runtime toggling myself is that I am afraid our two rendering codebases will diverge too much, making backporting that much harder. So it would be best for you to add the runtime setting instead so users can turn it on/off.

**Comment by inactive123** [comment]
@flyinghead Wow, I think after backporting the trilinear commits to non-OIT, I think performance is no longer an issue anymore. If anything it seems like it's a bit faster than before even.

Never mind then, and I would suggest to @mlnlbrt that he checks tomorrow's cores to see how performance is for him now in light of these backports.

**Comment by mlnlbrt** [comment]
Well, I have checked https://github.com/libretro/reicast-emulator/commit/85553efec4c34dfdc4ab76c48cff6c068350494d (non-OIT only) and UT seems to be a little bit faster than in eariler versions, but I still have some stuttering here and there.

Let's say that the performance drop introduced in some recent commits is gone, but on the other hand, Cosmic Smash is almost unplayable (in terms of speed) :/ It worked fine earlier.

**Comment by inactive123** [comment]
Cosmic Smash is unplayable in terms of speed on which renderer? OIT or non-OIT? On OIT you will have to lower the resolution. Non-OIT I dunno, maybe @flyinghead could let me know if there is some performance-related issue there that I am missing.

**Comment by flyinghead** [comment]
Non-OIT should be playable. It works decently on a Raspberry Pi.

**Comment by mlnlbrt** [comment]
On non-OIT, I haven't checked OIT for Cosmic Smash recently

**Comment by flyinghead** [comment]
Assuming resolved. Reopen as needed
