### ISSUE TITLE
Graphical Glitch - Galaxy S7 (Exynos) Android Oreo- Vulkan Driver

### ISSUE THREAD

**Issue by tabnk** [libretro/flycast#793]
On Vulkan (Default Setting + WS Cheat), it have Graphical Glitch in all games. OpenGL is fine. 

Example:
Virtua Fighter 3.

![Screenshot_20200128-092122](https://user-images.githubusercontent.com/10874582/73227992-45d72a80-41b0-11ea-875b-4169d21d40f1.jpg)
![Screenshot_20200128-092127](https://user-images.githubusercontent.com/10874582/73227994-45d72a80-41b0-11ea-808f-025ff0953485.jpg)
![Screenshot_20200128-092133](https://user-images.githubusercontent.com/10874582/73227995-45d72a80-41b0-11ea-9181-ad6cac2b062c.jpg)

**Comment by flyinghead** [comment]
It's only happening on this platform so this is probably a Vulkan driver bug. I believe the Galaxy S7 has a Mali GPU so do you know the version of the Mali drivers used by your phone?

Check if a graphics driver or android update is available for your phone.

**Comment by tabnk** [comment]
Vulkan API 1.0.61
Version (hash) a4c0bd09.

It is latest version for this device.

**Comment by tabnk** [comment]
DriverVersion: 659.11.3337

**Comment by kage2051** [comment]
@tabnk 
There is still a chance for the OEM to update the GPU drivers on Exynos S7 models, since it's currently getting quarterly security updates. But to be honest, it might not be a huge driver update because the Mali-T880 GPU used by your phone is quite old (was released in late 2015) and Vulkan versions beyond 1.0 need at least Android 9 Pie anyway.

BTW, are you using stock ROM from Samsung or a custom ROM e.g. LineageOS?

**Comment by tabnk** [comment]
On Stock Oreo 8.0. 

Saw a youtube video with LineageOS PIE driver had slower gaming performance than Stock so no point to install.

**Comment by tabnk** [comment]
Decided to ditch STOCK OS (Oreo) and upgraded to **LineageOS 18.1 for S7 Exynos**  https://forum.xda-developers.com/t/rom-stable-signature-spoofing-microg-support-lineageos-18-1-for-s7-exynos.4172749/ but same old glitch as stock.

Stock OS: Vulkan API 1.0.**61**
LineageOS 18.1: Vulkan API 1.0.**82**

Nevermind then.
