### ISSUE TITLE
Texture warping in CVSPRO+MVC2 (only on higher resolution)

### ISSUE THREAD

**Issue by Immersion95** [libretro/flycast#818]
Hi,

Recent commits instroduce texture warpings in some sprites on higher resolution.

**Examples :**
Ryu's standing pose in MVC2
Chun-Li's standing pose in CVSPRO

These bugs weren't present before, I don't don't know when exactly.

Tested it in Android+Windows (GL+Vulkan).

Thanks !

**Comment by aneronds** [comment]
I was going to post the same issue, even took a few pictures. As you said, it only happens when the internal res is higher than native, I am using 960. I play these games almost everyday and around a week ago I've updated my cores, I am pretty sure one of the last commits, which added the mipmapping and the power vr filter, is related.

![Capcom vs  SNK Pro (JPN)-200215-113402](https://user-images.githubusercontent.com/61091764/74592658-22aad880-5002-11ea-80e6-fe2695f9b89b.png)
![Marvel vs  Capcom 2 (USA)-200215-114435](https://user-images.githubusercontent.com/61091764/74592661-28082300-5002-11ea-8956-98bc511d4c3a.png)

**Comment by Immersion95** [comment]
Do you know if there is an option to solve this ? Maybe regarding mipmapping ?

**Comment by flyinghead** [comment]
I doubt this is due to mipmapping as these 2D games don't use mipmaps. And the power VR filter has no effect if disabled. It may be due to this change https://github.com/libretro/flycast/commit/a2137ce23b71b3d13857a770a6f13e6e68158850.

**Comment by Immersion95** [comment]
Great !

Would it be possible to revert that change ?

**Comment by Immersion95** [comment]
Any news regarding this issue ? MVC2 can't have increased resolution because of this and it's a shame :p

**Comment by flyinghead** [comment]
I checked the commit mentioned above and it's not the culprit.

I went further back in the commit history and I can't find any version that doesn't have glitch when upscaling this game.

**Comment by Immersion95** [comment]
What is the last one that you tested ? I'm almost certain that it wasn't there 1 year ago.

**Comment by flyinghead** [comment]
I can't remember where I stopped exactly. Probably late 2019/early 2020.

**Comment by Immersion95** [comment]
Hi, is there anyway to pinpoint this problem ? I would love to try the different revisions to find where it fails but I don't know how to build those. Is there any guide I could follow ? Thanks !
