### ISSUE TITLE
Sonic Adventure (NTSC/PAL) crash after logo

### ISSUE THREAD

**Issue by Neroga** [libretro/flycast#847]
Unable to play Sonic Adventure. Right after the SEGA logos disappear. Me thinks it's the FMV as they work perfectly fine on the Windows build. RetroArch pops up saying "The software was closed because an error occured." Happens on all copies in GDI, CDI, and CHD format. 

Playing on Nintendo Switch FW 9.1.0 Atmosphere 10.4

**Comment by ghost** [comment]
Same issue happens for me. every other game works.

After selecting 50hz or 60hz, HOS error appears. tried updating and trying different games and rom versions.

**Comment by flyinghead** [comment]
Seems to be specific to the Switch, and I don't own one so I can't test.

Can you post a verbose log?

**Comment by ghost** [comment]
https://paste.ubuntu.com/p/mpMpDfj8ft/

**Comment by flyinghead** [comment]
Please try the build at: https://git.m4xw.net/libretro/cores/flycast/-/jobs/7342/artifacts/browse

It may also crash but the log should tell us more about the issue.

Thanks

**Comment by ghost** [comment]
https://paste.ubuntu.com/p/N9RkYZmJw5/

Shows the FMV

 and gets in-game with no problems.

The only real issue that isn't a huge deal, for the time being, is when you close content it segfaults to the HOS "the software was closed because an error occurred.

![D8EfgGb](https://user-images.githubusercontent.com/40307312/77570133-87224880-6e88-11ea-9e50-2cebf744882b.jpg)

**Comment by ghost** [comment]
closed for me. @Neroga ?

**Comment by AlmondMilk12** [comment]
That other build seems to work fine

**Comment by ghost** [comment]
Updating from the build bot the issue now appears after selecting sonic and emerald coast. Segfaults before the level loads. Will pull a log tonight.

**Comment by flyinghead** [comment]
Closing as resolved. Reopen as needed
