### ISSUE TITLE
Dead or Alive 2 (PAL) - Inputs don't work correctly

### ISSUE THREAD

**Issue by inactive123** [libretro/flycast#93]
I can select a character and I can get ingame, however, I cannot punch or kick. Nearly all the buttons just correspond to Blocking.

Weird how this is the only version of the game that has these problems. Dead or Alive 2 (US), Dead or Alive 2 LE (Japan), Dead or Alive 2 (Naomi) and Dead or Alive 2 Millennium (Naomi) all seem to be fine.

**Comment by flyinghead** [comment]
Can't reproduce. Test and reopen as needed

**Comment by cosmocanyon** [comment]
I got the same problem with the last build v2.2

To reproduce problem it's necessary Dead or Alive 2 PAL and Dead or Alive 2 USA.

How I reproduced the problem.
Delete all save game files created in the flycast folder for the games.
Start DOA2 USA.
Create save game. 
Play (training mode).
Exit.
Load DOA2 PAL
Create save game.
Play (training mode).
Each button is block.
In the options controller the buttons are recorded rightfully, only in game is always blocking.

You can reproduce the same issue with the games ordered the other way around.
If you play DOA PAL before and after DOA USA, it's the second game having the button blocking issue. 

The game that shows the issue has also another problem in the story mode, the matches start with time at 00s instead of 90s, instant lose.

I also tried with DOA Japan Shokai Genteiban and doesn't create the issue with other two versions.

**Comment by barbudreadmon** [comment]
@cosmocanyon if you want your issue to be looked into, i'd recommend posting in the correct repo instead of bumping a dead issue in a dead repo.
